import type { CapturedCookie, SocialProvider } from "@/lib/social/providers"

/**
 * Normalizes parsed cookies into the Netscape file `yt-dlp
 * --cookies` reads (SESSION_AUTH.md §3).
 *
 * NOTHING HERE MAY BE LOGGED. A serialized jar is the whole credential —
 * strictly more dangerous than an API key, because it is a bearer token
 * for the user's entire social account.
 */

/** Cookies whose domain is outside the provider's list are discarded. */
function inScope(cookie: CapturedCookie, provider: SocialProvider): boolean {
  const domain = cookie.domain.toLowerCase()
  return provider.cookieDomains.some((allowed) => {
    const target = allowed.toLowerCase()
    // A leading dot means "and every subdomain".
    if (target.startsWith(".")) {
      return domain === target || domain.endsWith(target)
    }
    return domain === target || domain === `.${target}`
  })
}

/**
 * A tab character separates Netscape fields, so a value containing one
 * would silently shift every later column. Chrome will not produce such a
 * cookie, but a corrupt jar must fail loudly rather than be written wrong.
 */
function assertSerializable(cookie: CapturedCookie): void {
  if (/[\t\r\n]/.test(cookie.value) || /[\t\r\n]/.test(cookie.name)) {
    throw new Error(
      `Cookie "${cookie.name}" contains a tab or newline and cannot be written to a Netscape jar`,
    )
  }
}

export interface SerializedJar {
  /** The whole file. Treat as radioactive — encrypt, never log. */
  contents: string
  /** Names only, for diagnostics. Never values. */
  cookieNames: string[]
  /**
   * Earliest expiry among the provider's session cookies, in ms — or null
   * when they are all session cookies. This is what lands in
   * `credentials.expires_at`: a floor on uselessness, NOT a promise of
   * validity, since a session can be revoked server-side at any time.
   */
  expiresAt: number | null
}

export function toNetscapeJar(
  cookies: readonly CapturedCookie[],
  provider: SocialProvider,
): SerializedJar {
  const scoped = cookies.filter((cookie) => inScope(cookie, provider))
  for (const cookie of scoped) assertSerializable(cookie)

  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by Relay. Do not edit.",
    "",
  ]

  for (const cookie of scoped) {
    // `#HttpOnly_` is the curl/Chrome convention for an HttpOnly cookie and
    // yt-dlp understands it. It matters: Instagram's `sessionid` IS
    // HttpOnly, so dropping the prefix (or the cookie) loses the session.
    const domain = `${cookie.httpOnly ? "#HttpOnly_" : ""}${cookie.domain}`
    // Field 2 is "does every host in the domain match", which is exactly
    // what a leading dot means.
    const includeSubdomains = cookie.domain.startsWith(".") ? "TRUE" : "FALSE"
    // A session cookie is expiry 0 in this format.
    const expires = cookie.expires > 0 ? Math.floor(cookie.expires) : 0
    lines.push(
      [
        domain,
        includeSubdomains,
        cookie.path || "/",
        cookie.secure ? "TRUE" : "FALSE",
        String(expires),
        cookie.name,
        cookie.value,
      ].join("\t"),
    )
  }

  const sessionExpiries = scoped
    .filter((cookie) => provider.sessionCookies.includes(cookie.name))
    .map((cookie) => cookie.expires)
    .filter((expires) => expires > 0)

  return {
    contents: `${lines.join("\n")}\n`,
    cookieNames: scoped.map((cookie) => cookie.name),
    expiresAt:
      sessionExpiries.length > 0
        ? Math.floor(Math.min(...sessionExpiries) * 1000)
        : null,
  }
}

/** Every cookie the provider needs is present — i.e. the login finished. */
export function isComplete(
  cookies: readonly CapturedCookie[],
  provider: SocialProvider,
): boolean {
  const names = new Set(
    cookies.filter((c) => inScope(c, provider)).map((c) => c.name),
  )
  return provider.sessionCookies.every((name) => names.has(name))
}
